### ISSUE TITLE
Does this package work with Angular 4?

### ISSUE THREAD

**Issue by gabrielalack** [AndyMeps/ng2-color-picker#9]
Just from following the basic instructions I get this on build:
`ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in .../node_modules/ng2-color-picker/node_modules/@angular/core/core.d.ts, resolving symbol ColorPickerModule in .../node_modules/ng2-color-picker/dist/src/color-picker.module.d.ts, resolving symbol ColorPickerModule in .../node_modules/ng2-color-picker/dist/src/color-picker.module.d.ts`

And when trying to run the app I'm getting
`Uncaught Error: Unexpected value 'ColorPickerModule' imported by the module 'AppModule'. Please add a @NgModule annotation.
    at syntaxError (http://localhost:4200/vendor.bundle.js:9164:34)
    at http://localhost:4200/vendor.bundle.js:22118:44
    at Array.forEach (native)
    at CompileMetadataResolver.webpackJsonp../node_modules/@angular/compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:22101:49)
    at JitCompiler.webpackJsonp../node_modules/@angular/compiler/@angular/compiler.es5.js.JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:33254:66)
    at JitCompiler.webpackJsonp../node_modules/@angular/compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (http://localhost:4200/vendor.bundle.js:33213:52)
    at JitCompiler.webpackJsonp../node_modules/@angular/compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:33175:23)
    at PlatformRef_.webpackJsonp../node_modules/@angular/core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone (http://localhost:4200/vendor.bundle.js:39074:25)
    at PlatformRef_.webpackJsonp../node_modules/@angular/core/@angular/core.es5.js.PlatformRef_.bootstrapModule (http://localhost:4200/vendor.bundle.js:39060:21)`

**Comment by tornord** [comment]
Still exactly the same error

**Comment by gabrielalack** [comment]
Try PrimNG's color picker. It's pretty clean.
